import { expect, test, type Page } from '@playwright/test';
import { UI_MATRIX_CASES } from '../matrix-cases';
import {
  closeDesktopUiMatrix,
  desktopWorkspaceCounts,
  firstActiveCatalogTargets,
  launchDesktopUiMatrix,
} from '../helpers/desktop';
import {
  assertUiStable,
  captureUi,
  navigateHashRoute,
  scrollMainSurface,
  verifyBackForward,
} from '../helpers/runtime-guards';

const generatedFixtureSizes = ['minimal', 'medium', 'heavy'] as const;

type GeneratedFixtureSize = typeof generatedFixtureSizes[number];

function generatedCaptureName(fixtureSize: GeneratedFixtureSize, capture: string) {
  return `generated-${fixtureSize}-${capture}`;
}

async function assertGeneratedRoute(page: Page, route: `/${string}`, hasObservations: boolean) {
  if (route === '/') {
    await expect(page.getByText('Command home')).toBeVisible();
    await expect(page.getByRole('link', { name: /Open Products/i })).toBeVisible();
    await expect(page.getByRole('link', { name: /Open Inventory/i })).toHaveAttribute('href', /#\/insights\/inventory/);
    await expect(page.getByRole('link', { name: /Open Insights/i })).toHaveCount(0);
    return;
  }
  if (route === '/work/queue') {
    if (hasObservations) {
      await expect(page.getByRole('heading', { name: 'Queue' })).toBeVisible();
      await expect(page.getByRole('searchbox', { name: 'Search queue' })).toBeVisible();
    } else {
      await expect(page.getByText('Work needs your first update')).toBeVisible();
      await expect(page.getByRole('link', { name: 'Start update' })).toBeVisible();
    }
    return;
  }
  if (route === '/work/capture') {
    await expect(page.getByRole('link', { name: 'Products Update' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Supplier Order' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Customer Order' })).toBeVisible();
    return;
  }
  if (route === '/catalog') {
    await expect(page.getByText('Offered Selections')).toBeVisible();
    await expect(page.getByRole('searchbox', { name: 'Search products' })).toBeVisible();
    await expect(page.getByRole('combobox', { name: 'Filter by supplier' })).toBeVisible();
    return;
  }
  if (route === '/insights') {
    await expect(page.getByText('Understand what needs attention')).toBeVisible();
    await expect(page.getByRole('link', { name: 'Inventory' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Money' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Explain' })).toBeVisible();
    return;
  }
  if (route === '/insights/inventory') {
    await expect(page.getByRole('heading', { name: hasObservations ? 'Inventory' : 'Inventory analysis is not ready yet.' })).toBeVisible();
    if (hasObservations) {
      await expect(page.getByText('Inventory health grid')).toBeVisible();
    }
    return;
  }
  if (route === '/insights/money') {
    await expect(page.getByText(hasObservations ? 'Money' : 'Money needs the first SENA run', { exact: true }).first()).toBeVisible();
    if (hasObservations) {
      await expect(page.getByRole('combobox', { name: 'Select financials time range' })).toBeVisible();
    }
    return;
  }
  if (route === '/insights/explain') {
    await expect(page.getByText(hasObservations ? 'Explain' : 'Explain needs the first SENA run', { exact: true }).first()).toBeVisible();
    return;
  }
  if (route.startsWith('/settings/history')) {
    await expect(page.getByText('History', { exact: true }).first()).toBeVisible();
    await expect(page.getByRole('searchbox', { name: 'Search observations' })).toBeVisible();
    if (!hasObservations) {
      await expect(page.getByText('No observations match the current filters.')).toBeVisible();
    }
    return;
  }
  if (route === '/settings/automation') {
    await expect(page.getByText(/Automated Telegram Bot|Automations and intake/).first()).toBeVisible();
  }
}

test.describe('UI matrix: desktop autogenerated state', () => {
  for (const fixtureSize of generatedFixtureSizes) {
    test(`generated ${fixtureSize} workspace route sweep and controls stay stable`, async ({}, testInfo) => {
      testInfo.annotations.push({
        type: 'ui-matrix',
        description: UI_MATRIX_CASES.find((entry) => entry.id === 'desktop-generated-route-and-control-sweep')?.expectedUi ?? '',
      });

      const launched = await launchDesktopUiMatrix({
        fixtureSize,
        name: `desktop-generated-${fixtureSize}`,
        testInfo,
      });

      try {
        await launched.page.waitForLoadState('domcontentloaded');
        const counts = await desktopWorkspaceCounts(launched.page);
        expect(counts.skuCount, 'generated fixture should include SKUs').toBeGreaterThan(0);
        expect(counts.serviceCount, 'generated fixture should include services').toBeGreaterThan(0);
        expect(counts.observationCount, `${fixtureSize} generated fixture should include observations`).toBeGreaterThan(0);
        if (fixtureSize !== 'minimal') {
          expect(counts.summaryIntervalCount, `${fixtureSize} generated fixture should include summary intervals`).toBeGreaterThan(0);
        }

        const targets = await firstActiveCatalogTargets(launched.page);
        expect(targets.skuId, 'generated fixture should expose an active SKU detail target').toBeTruthy();
        expect(targets.serviceId, 'generated fixture should expose an active service detail target').toBeTruthy();
        const hasObservations = counts.observationCount > 0;

        const routes: Array<{ capture: string; route: `/${string}` }> = [
          { route: '/', capture: 'home' },
          { route: '/work/capture', capture: 'capture-hub' },
          { route: '/catalog', capture: 'catalog' },
          { route: '/insights', capture: 'insights' },
          { route: '/insights/money', capture: 'insights-money' },
          { route: '/settings/history?view=all', capture: 'history' },
          { route: '/settings/automation', capture: 'automation-settings' },
          { route: '/insights/inventory', capture: 'insights-inventory' },
          { route: '/work/queue', capture: 'work-queue' },
          { route: '/insights/explain', capture: 'insights-explain' },
        ];

        for (const routeCase of routes) {
          await navigateHashRoute(launched.page, routeCase.route);
          await assertGeneratedRoute(launched.page, routeCase.route, hasObservations);
          await scrollMainSurface(launched.page);
          await assertUiStable(launched.page, `generated route ${routeCase.route}`);
          await captureUi(launched.page, testInfo, generatedCaptureName(fixtureSize, routeCase.capture));
        }

        await navigateHashRoute(launched.page, '/catalog');
        await launched.page.getByRole('searchbox', { name: 'Search products' }).fill('krama');
        await expect(launched.page.getByRole('searchbox', { name: 'Search products' })).toHaveValue('krama');
        await launched.page.getByRole('combobox', { name: 'Filter by supplier' }).click();
        await launched.page.keyboard.press('Escape');
        await assertUiStable(launched.page, 'generated catalog search and supplier controls');

        await navigateHashRoute(launched.page, `/catalog/skus/${targets.skuId}`);
        await expect(launched.page.getByRole('heading').first()).toBeVisible();
        await expect(launched.page.getByRole('button', { name: 'Record' })).toBeVisible();
        await assertUiStable(launched.page, 'generated SKU detail');
        await captureUi(launched.page, testInfo, generatedCaptureName(fixtureSize, 'sku-detail'));

        await navigateHashRoute(launched.page, `/catalog/services/${targets.serviceId}`);
        await expect(launched.page.getByRole('heading').first()).toBeVisible();
        await expect(launched.page.getByRole('button', { name: 'Record' })).toBeVisible();
        await assertUiStable(launched.page, 'generated service detail');
        await captureUi(launched.page, testInfo, generatedCaptureName(fixtureSize, 'service-detail'));

        await verifyBackForward(launched.page, '/catalog', '/insights/explain');
        launched.issues.assertNoIssues(`generated ${fixtureSize} desktop matrix`);
      } finally {
        await closeDesktopUiMatrix(launched);
      }
    });
  }
});
