export type UiMatrixProductTarget = 'desktop' | 'browser-app' | 'demo-browser' | 'mobile';
export type UiMatrixDataState = 'fresh' | 'autogenerated' | 'dependent';
export type UiMatrixPriority = 'P0' | 'P1' | 'P2';
export type UiMatrixTestType = 'smoke' | 'regression' | 'visual' | 'interaction' | 'stateful' | 'end-to-end';

export interface UiMatrixCase {
  id: string;
  productTarget: UiMatrixProductTarget;
  dataState: UiMatrixDataState;
  area: string;
  initialData: string;
  interaction: string;
  expectedUi: string;
  expectedState: string;
  consistency: string;
  priority: UiMatrixPriority;
  testTypes: UiMatrixTestType[];
  captures: string[];
  edgeNotes: string;
}

export const UI_MATRIX_CASES: UiMatrixCase[] = [
  {
    id: 'desktop-fresh-first-run-empty-routes',
    productTarget: 'desktop',
    dataState: 'fresh',
    area: 'Onboarding, empty workspace, guarded routes',
    initialData: 'Isolated empty desktop data directory with no generated history.',
    interaction: 'Complete onboarding, navigate empty routes, open disabled or empty surfaces, resize and scroll.',
    expectedUi: 'No crash, no NaN, no broken charts, no document overflow, and empty-state guidance remains visible.',
    expectedState: 'Preferences persist onboarding completion while catalog, observations, and order batches remain empty.',
    consistency: 'Bridge counts agree with empty route state after reload.',
    priority: 'P0',
    testTypes: ['smoke', 'visual', 'interaction', 'stateful'],
    captures: ['onboarding', 'home', 'catalog-new-sku', 'work', 'settings-history'],
    edgeNotes: 'Fresh route guards may redirect unavailable pages to create/setup routes.',
  },
  {
    id: 'desktop-generated-route-and-control-sweep',
    productTarget: 'desktop',
    dataState: 'autogenerated',
    area: 'Generated workspace route sweep and major controls',
    initialData: 'Deterministic generated history fixture.',
    interaction: 'Visit major routes, open detail pages, use search/filter/dropdown controls, open drawers where data allows.',
    expectedUi: 'Populated tables, charts, cards, drawers, and details remain stable with captures.',
    expectedState: 'Generated catalog, observation, summary, and detail data remain readable across route changes.',
    consistency: 'Catalog counts and first detail ids match bridge probes across Catalog and detail pages.',
    priority: 'P0',
    testTypes: ['regression', 'visual', 'interaction'],
    captures: ['home', 'work-queue', 'catalog', 'sku-detail', 'service-detail', 'insights'],
    edgeNotes: 'Run medium by default; heavier fixtures can be selected by environment or focused command.',
  },
  {
    id: 'desktop-dependent-organic-update-chain',
    productTarget: 'desktop',
    dataState: 'dependent',
    area: 'Organic catalog and record-update state propagation',
    initialData: 'Fresh workspace with onboarding skipped as setup only.',
    interaction: 'Create SKU and service through UI, edit SKU pricing, save stock count through UI, reload and cross-check routes.',
    expectedUi: 'New entities and updates appear in Catalog, detail, Work/Capture, Inventory, and Logs without stale state.',
    expectedState: 'Catalog and observation counts increase; saved values persist after reload.',
    consistency: 'Bridge probes agree with visible entity names and observation/history surfaces.',
    priority: 'P0',
    testTypes: ['stateful', 'end-to-end', 'regression', 'visual'],
    captures: ['sku-form', 'service-form', 'stock-count-review', 'catalog-after-reload', 'history'],
    edgeNotes: 'Order/receipt subflows can extend this chain without changing helper contracts.',
  },
  {
    id: 'web-demo-and-browser-parity',
    productTarget: 'demo-browser',
    dataState: 'autogenerated',
    area: 'Demo and browser app banners, local-first controls, major route parity',
    initialData: 'Browser embedded runtime fallback/demo state.',
    interaction: 'Open /demo and /app, inspect banners, reset/import/export controls, navigate populated routes.',
    expectedUi: 'Demo/browser banners and controls remain visible, routes render, and local-first copy is present.',
    expectedState: 'Demo state stays separate from browser-app state.',
    consistency: 'Major routes expose the same navigation families as desktop where supported.',
    priority: 'P1',
    testTypes: ['smoke', 'visual', 'interaction'],
    captures: ['demo-home', 'demo-catalog', 'app-onboarding-or-home'],
    edgeNotes: 'Browser storage support is environment-dependent; fallback state is still a valid UI regression target.',
  },
  {
    id: 'mobile-responsive-embedded-layouts',
    productTarget: 'mobile',
    dataState: 'autogenerated',
    area: 'Phone portrait, phone landscape, and narrow responsive shells',
    initialData: 'Embedded demo/browser runtime at mobile viewports.',
    interaction: 'Resize to phone portrait and landscape, verify rotate prompt, banner controls, and responsive shell.',
    expectedUi: 'No incoherent overlap or document overflow; portrait prompt and landscape workspace remain stable.',
    expectedState: 'Responsive changes do not reset browser/demo workspace state.',
    consistency: 'Route hash survives viewport changes.',
    priority: 'P1',
    testTypes: ['visual', 'interaction', 'regression'],
    captures: ['phone-portrait-rotate', 'phone-landscape-demo', 'tablet-browser-app'],
    edgeNotes: 'Pixel baselines are intentionally deferred; captures are diagnostic artifacts.',
  },
];
